source 'https://rubygems.org'

gem 'rails', '4.2'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'active_service', git: 'git@github.com:zacharywelch/activeservice.git'
gem 'faraday_middleware'
gem 'responders'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
end
